"""
Django settings for crkva project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from typing import List

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(DEBUG=(bool, False))

# Read .env file from project root (two levels up from settings.py)
environ.Env.read_env(os.path.join(BASE_DIR.parent, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG", 0)))

# Тест-рунери (manage.py test / pytest) форсирају DEBUG=False, па би
# продукцијско учвршћивање испод иначе укључило SSL redirect и празан
# ALLOWED_HOSTS усред тестова. Откривамо тест-рун да то избегнемо (#223).
_RUNNING_TESTS = "test" in sys.argv or sys.argv[0].endswith(("pytest", "py.test"))


def _require_env(name):
    """Враћа обавезну променљиву окружења или одмах пуца са јасном поруком (#292)."""
    value = os.environ.get(name)
    if not value:
        raise ImproperlyConfigured(
            f"Недостаје обавезна променљива окружења: {name}. "
            "Подеси је у .env или у окружењу пре покретања."
        )
    return value


# SECURITY WARNING: keep the secret key used in production secret!
# У продукцији је SECRET_KEY обавезан (пуца одмах ако недостаје); у DEBUG-у и
# при тестовима користи се небезбедан развојни кључ ради лакшег покретања (#292).
if DEBUG or _RUNNING_TESTS:
    SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-only-key")
else:
    SECRET_KEY = _require_env("SECRET_KEY")
    # #337: одбиј познате небезбедне подразумеване кључеве у продукцији.
    # (Compose профили су раније убацивали фиксни кључ, чиме је _require_env
    # био задовољен познатом вредношћу.)
    _INSECURE_SECRET_KEYS = {
        "insecure-standalone-key-change-me",
        "dev-secret-key-change-me",
        "django-insecure-dev-only-key",
    }
    if SECRET_KEY in _INSECURE_SECRET_KEYS or SECRET_KEY.startswith("django-insecure"):
        raise ImproperlyConfigured(
            "SECRET_KEY је постављен на познату небезбедну вредност; "
            "постави јединствен тајни кључ у окружењу пре продукције."
        )

# Калибрационе странице (крштеница/венчаница) су подразумевано искључене у
# продукцији; могу се привремено укључити поставком CALIBRATION_ENABLED=1 у
# окружењу (нпр. .env + reload) ради калибрације на живом серверу (#16/#17).
CALIBRATION_ENABLED = DEBUG or os.environ.get("CALIBRATION_ENABLED", "0") == "1"

# Продукција прихвата само хостове из ALLOWED_HOSTS env; dev/тест дозвољавају све.
ALLOWED_HOSTS: List[str] = list(
    filter(None, os.environ.get("ALLOWED_HOSTS", "").split(","))
)
if DEBUG or _RUNNING_TESTS:
    ALLOWED_HOSTS = ALLOWED_HOSTS or ["*"]

# Behind Caddy, which terminates TLS and reverse-proxies plain HTTP to
# gunicorn. Trust its X-Forwarded-Proto header so request.is_secure(),
# CSRF origin checks, and secure cookies work over the HTTPS hostname.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = list(
    filter(None, os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(","))
)

# Продукцијско безбедносно учвршћивање (#223). HTTPS-учвршћивање контролише
# флег SECURE_SSL (раздвојено од DEBUG — #7): подразумевано укључено ван
# DEBUG-а, искључено у DEBUG-у. Самосталне инсталације преко plain HTTP на
# localhost-у постављају SECURE_SSL=0. TLS терминира Caddy, па се ово ослања
# на горњи SECURE_PROXY_SSL_HEADER (Caddy шаље X-Forwarded-Proto=https).
SECURE_SSL = (os.environ.get("SECURE_SSL") or ("0" if DEBUG else "1")) == "1"
if SECURE_SSL and not _RUNNING_TESTS:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 година
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Application definition

# django-tenants: SHARED_APPS live in the public schema (visible to every
# tenant); TENANT_APPS get their own copy in each tenant's Postgres schema.
SHARED_APPS = [
    "django_tenants",  # MUST be first
    "tenants",  # Parohija + Domen + Clanstvo
    "kalendar",  # Slava (дани поста) — canonical list, shared across tenants
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_typer",
    "compressor",
    "import_export",
    "django_select2",
    "admin_searchable_dropdown",
    "simple_history",
    "phonenumber_field",
    "axes",  # rate-limit/lockout on failed logins; admin UI under /admin/axes/
]

TENANT_APPS = [
    "registar",
]

INSTALLED_APPS = list(SHARED_APPS) + [a for a in TENANT_APPS if a not in SHARED_APPS]

TENANT_MODEL = "tenants.Zakupac"
TENANT_DOMAIN_MODEL = "tenants.Domen"

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tenants.middleware.SessionTenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "registar.middleware.HandleMissingTablesMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "axes.middleware.AxesMiddleware",  # must be LAST per django-axes docs
]

ROOT_URLCONF = "crkva.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tenants.context_processors.current_tenant",
            ],
        },
    },
]

WSGI_APPLICATION = "crkva.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

SCHEMA = os.environ.get("DB_SCHEMA")
DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
        "HOST": _require_env("DB_HOST"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "NAME": _require_env("DB_NAME"),
        "USER": _require_env("DB_USER"),
        "PASSWORD": _require_env("DB_PASS"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authentication redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "pocetna"
LOGOUT_REDIRECT_URL = "login"


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "sr"

TIME_ZONE = "Europe/Amsterdam"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/static/"
MEDIA_URL = "static/media/"

STATIC_ROOT = os.environ.get("STATIC_ROOT", "/vol/web/static/")
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", "/vol/web/media/")

# Staticfiles finders (include compressor)
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

# Django Compressor settings
COMPRESS_ENABLED = True
# In development, keep offline compression disabled. For production, set to True
# and run `python manage.py compress` during build/deploy.
COMPRESS_OFFLINE = False
COMPRESS_CSS_FILTERS = [
    "compressor.filters.css_default.CssAbsoluteFilter",
    "compressor.filters.cssmin.rCSSMinFilter",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


FIXTURE_DIRS = [os.path.join(BASE_DIR, "fixtures")]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "tenants": {
            "handlers": ["console"],
            "level": "WARNING",
        },
        "registar": {
            "handlers": ["console"],
            "level": "WARNING",
        },
    },
}

TEST_RUNNER = "tenants.test_runner.TenantTestRunner"


# ---------------------------------------------------------------------------
# Caches
# ---------------------------------------------------------------------------
# django-select2 signs every heavy <select> with a field_id and stores the
# widget's queryset metadata in Django's cache under that key. The browser
# then GETs /select2/fields/auto.json?field_id=… and the server must look
# the key up to know what to return.
#
# The default cache backend is LocMemCache which is per-process, so under
# multi-worker gunicorn (workers=3 in scripts/gunicorn.conf.py) a field_id
# minted by worker A is invisible to workers B and C, producing a 404 with
# "field_id not found" on roughly 67% of AJAX requests. Symptom: the
# Hram / Svestenik / Osoba autocomplete dropdowns silently show "Грешка
# при учитавању резултата" (or nothing) on /unos/krstenje/ and friends.
#
# The fix is any cross-process cache. FileBasedCache works on the bare
# systemd host with zero extra services. The DB layer is per-tenant so we
# cannot use DatabaseCache here without extra plumbing.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.environ.get(
            "DJANGO_CACHE_DIR", str(BASE_DIR.parent / ".django_cache")
        ),
        "TIMEOUT": 60 * 60 * 8,  # 8h — matches a typical workday session
        "OPTIONS": {"MAX_ENTRIES": 5000},
    }
}


# django-axes: brute-force protection on login. AxesStandaloneBackend must be
# first; ModelBackend stays as the fallback for actual authentication.
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True

# Disable django-axes during the test suite. The Django test client's
# login() does not pass a request to the auth backend, but AxesBackend
# requires one (raises AxesBackendRequestParameterRequired otherwise).
if "test" in sys.argv:
    AXES_ENABLED = False
    # Тестови намерно изазивају 403/404 (провере дозвола и непостојећих
    # записа). Django их бележи са traceback-ом (ERROR) односно упозорењем
    # (WARNING) преко django.request. Утишај тај логер у тестовима да CI
    # лог остане читљив — стварне грешке се и даље виде као неуспели тестови.
    LOGGING["loggers"]["django.request"] = {
        "handlers": ["console"],
        "level": "CRITICAL",
        "propagate": False,
    }
