"""
Django settings for crkva project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from typing import List

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(DEBUG=(bool, False))

# Read .env file from project root (two levels up from settings.py)
environ.Env.read_env(os.path.join(BASE_DIR.parent, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG", 0)))

ALLOWED_HOSTS: List[str] = ["*"]
ALLOWED_HOSTS.extend(filter(None, os.environ.get("ALLOWED_HOSTS", "").split(",")))

# Application definition

# django-tenants: SHARED_APPS live in the public schema (visible to every
# tenant); TENANT_APPS get their own copy in each tenant's Postgres schema.
SHARED_APPS = [
    "django_tenants",  # MUST be first
    "tenants",  # Tenant + Domain + UserMembership
    "kalendar",  # Slava (saint feast day) — canonical list, shared across tenants
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "compressor",
    "import_export",
    "django_select2",
    "admin_searchable_dropdown",
    "django_filters",
    "phonenumber_field",
]

TENANT_APPS = [
    "registar",
]

INSTALLED_APPS = list(SHARED_APPS) + [a for a in TENANT_APPS if a not in SHARED_APPS]

TENANT_MODEL = "tenants.Tenant"
TENANT_DOMAIN_MODEL = "tenants.Domain"

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tenants.middleware.SessionTenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "registar.middleware.HandleMissingTablesMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "crkva.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "registar.context_processors.processor_narednih_slava",
                "tenants.context_processors.current_tenant",
            ],
        },
    },
]

WSGI_APPLICATION = "crkva.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

SCHEMA = os.environ.get("DB_SCHEMA")
DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "OPTIONS": {
            "client_encoding": "UTF8",
        },
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASS"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authentication redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "pocetna"
LOGOUT_REDIRECT_URL = "login"


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "sr"

TIME_ZONE = "Europe/Amsterdam"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/static/"
MEDIA_URL = "static/media/"

STATIC_ROOT = os.environ.get("STATIC_ROOT", "/vol/web/static/")
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", "/vol/web/media/")

# Staticfiles finders (include compressor)
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]

# Django Compressor settings
COMPRESS_ENABLED = True
# In development, keep offline compression disabled. For production, set to True
# and run `python manage.py compress` during build/deploy.
COMPRESS_OFFLINE = False
COMPRESS_CSS_FILTERS = [
    "compressor.filters.css_default.CssAbsoluteFilter",
    "compressor.filters.cssmin.rCSSMinFilter",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


FIXTURE_DIRS = [os.path.join(BASE_DIR, "fixtures")]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
        },
    },
    "django": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}

TEST_RUNNER = "tenants.test_runner.TenantTestRunner"


# ---------------------------------------------------------------------------
# Caches
# ---------------------------------------------------------------------------
# django-select2 signs every heavy <select> with a field_id and stores the
# widget's queryset metadata in Django's cache under that key. The browser
# then GETs /select2/fields/auto.json?field_id=… and the server must look
# the key up to know what to return.
#
# The default cache backend is LocMemCache which is per-process, so under
# multi-worker gunicorn (workers=3 in scripts/gunicorn.conf.py) a field_id
# minted by worker A is invisible to workers B and C, producing a 404 with
# "field_id not found" on roughly 67% of AJAX requests. Symptom: the
# Hram / Svestenik / Osoba autocomplete dropdowns silently show "Грешка
# при учитавању резултата" (or nothing) on /unos/krstenje/ and friends.
#
# The fix is any cross-process cache. FileBasedCache works on the bare
# systemd host with zero extra services. The DB layer is per-tenant so we
# cannot use DatabaseCache here without extra plumbing.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.environ.get(
            "DJANGO_CACHE_DIR", "/tmp/django_cache_spc_registar"
        ),
        "TIMEOUT": 60 * 60 * 8,  # 8h — matches a typical workday session
        "OPTIONS": {"MAX_ENTRIES": 5000},
    }
}
