# Generated by Django 6.0.1 on 2026-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kalendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slava",
            name="naziv",
            field=models.CharField(max_length=200, verbose_name="назив"),
        ),
        migrations.AlterField(
            model_name="slava",
            name="opsti_naziv",
            field=models.CharField(max_length=200, verbose_name="општи назив"),
        ),
    ]
