# Generated by Django 6.0.1 on 2026-07-14 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kalendar", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slava",
            old_name="offset_dani",
            new_name="pomak_dani",
        ),
        migrations.RenameField(
            model_name="slava",
            old_name="offset_nedelje",
            new_name="pomak_nedelje",
        ),
    ]
