# Generated by Django 5.1.15 on 2026-01-12 14:52

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Narodnost",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="народност")),
            ],
            options={
                "verbose_name": "Народност",
                "verbose_name_plural": "Народности",
                "db_table": "narodnosti",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Veroispovest",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="вероисповест"),
                ),
            ],
            options={
                "verbose_name": "Вероисповест",
                "verbose_name_plural": "Вероисповести",
                "db_table": "veroispovesti",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Zanimanje",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sifra", models.CharField(verbose_name="шифра")),
                ("naziv", models.CharField(max_length=255, verbose_name="назив")),
                (
                    "zenski_naziv",
                    models.CharField(null=True, verbose_name="женски назив"),
                ),
            ],
            options={
                "verbose_name": "Занимање",
                "verbose_name_plural": "Занимања",
                "db_table": "zanimanja",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Adresa",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("broj", models.CharField(max_length=10, verbose_name="број")),
                (
                    "sprat",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="спрат"
                    ),
                ),
                (
                    "broj_stana",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="број_стана"
                    ),
                ),
                (
                    "dodatak",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="додатак"
                    ),
                ),
                (
                    "postkod",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="поштански број",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, null=True, verbose_name="примедба"),
                ),
            ],
            options={
                "verbose_name": "Адреса",
                "verbose_name_plural": "Адресе",
                "db_table": "adrese",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Drzava",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=100, unique=True, verbose_name="назив"),
                ),
                (
                    "izvorni_naziv",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="изворни назив",
                    ),
                ),
                (
                    "postkod_regex",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="регекс поштанског броја",
                    ),
                ),
            ],
            options={
                "verbose_name": "Држава",
                "verbose_name_plural": "Државе",
                "db_table": "drzave",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Eparhija",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nivo",
                    models.CharField(
                        choices=[
                            ("Епархија", "Епархија"),
                            ("Архиепископија", "Архиепископија"),
                            ("Митрополија", "Митрополија"),
                        ],
                        default="Епархија",
                        max_length=15,
                        verbose_name="ниво",
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="назив")),
                ("sediste", models.CharField(max_length=100, verbose_name="седиште")),
            ],
            options={
                "verbose_name": "Епархија",
                "verbose_name_plural": "Епархије",
                "db_table": "eparhije",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Hram",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=200, verbose_name="назив")),
            ],
            options={
                "verbose_name": "Храм",
                "verbose_name_plural": "Храмови",
                "db_table": "hramovi",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Mesto",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="назив")),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "db_table": "mesta",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Opstina",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="назив")),
            ],
            options={
                "verbose_name": "Општина",
                "verbose_name_plural": "Општине",
                "db_table": "opstine",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Slava",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "uid",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("naziv", models.CharField(verbose_name="назив")),
                ("opsti_naziv", models.CharField(verbose_name="општи назив")),
                (
                    "dan",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="дан",
                    ),
                ),
                (
                    "mesec",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="месец",
                    ),
                ),
                (
                    "pokretni",
                    models.BooleanField(
                        default=False,
                        help_text="Празник који се рачуна у односу на Васкрс",
                        verbose_name="покретни празник",
                    ),
                ),
                (
                    "offset_dani",
                    models.IntegerField(
                        blank=True,
                        help_text="Број дана у односу на Васкрс",
                        null=True,
                        verbose_name="помак у данима",
                    ),
                ),
                (
                    "offset_nedelje",
                    models.IntegerField(
                        blank=True,
                        help_text="Број недеља у односу на Васкрс",
                        null=True,
                        verbose_name="помак у недељама",
                    ),
                ),
                ("post", models.BooleanField(default=False, verbose_name="пост")),
                (
                    "post_od",
                    models.IntegerField(
                        blank=True,
                        help_text="Почетак поста у данима од Васкрса",
                        null=True,
                        verbose_name="почетак поста (дани)",
                    ),
                ),
                (
                    "post_do",
                    models.IntegerField(
                        blank=True,
                        help_text="Крај поста у данима од Васкрса",
                        null=True,
                        verbose_name="крај поста (дани)",
                    ),
                ),
                (
                    "crveno_slovo",
                    models.BooleanField(
                        default=False,
                        help_text="Велики празник (црвено слово у календару)",
                        verbose_name="црвено слово",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слава",
                "verbose_name_plural": "Славе",
                "db_table": "slave",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CrkvenaOpstina",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="назив")),
                (
                    "eparhija",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.eparhija",
                        verbose_name="епархија",
                    ),
                ),
            ],
            options={
                "verbose_name": "Црквена општина",
                "verbose_name_plural": "Црквене општине",
                "db_table": "crkvene_opstine",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Osoba",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "uid",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("ime", models.CharField(max_length=100, verbose_name="име")),
                ("prezime", models.CharField(max_length=100, verbose_name="презиме")),
                (
                    "devojacko_prezime",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="девојачко презиме",
                    ),
                ),
                (
                    "parohijan",
                    models.BooleanField(
                        default=False,
                        help_text="Да ли је особа парохијанин",
                        verbose_name="парохијан",
                    ),
                ),
                (
                    "tel_fiksni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="мобилни телефон",
                    ),
                ),
                (
                    "slavska_vodica",
                    models.BooleanField(default=False, verbose_name="славска водица"),
                ),
                (
                    "uskrsnja_vodica",
                    models.BooleanField(default=False, verbose_name="ускршња водица"),
                ),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="место рођења",
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "vreme_rodjenja",
                    models.TimeField(
                        blank=True, null=True, verbose_name="време рођења"
                    ),
                ),
                (
                    "pol",
                    models.CharField(
                        blank=True,
                        choices=[("М", "мушки"), ("Ж", "женски")],
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                (
                    "zanimanje",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="занимање"
                    ),
                ),
                (
                    "veroispovest",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="вероисповест",
                    ),
                ),
                (
                    "narodnost",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="народност"
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.adresa",
                        verbose_name="адреса",
                    ),
                ),
                (
                    "slava",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.slava",
                        verbose_name="слава",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особа",
                "verbose_name_plural": "Особе",
                "db_table": "osobe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Parohija",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=200, verbose_name="назив")),
                (
                    "crkvena_opstina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.crkvenaopstina",
                        verbose_name="црквена општина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Парохија",
                "verbose_name_plural": "Парохије",
                "db_table": "parohije",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Domacinstvo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tel_fiksni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="мобилни телефон",
                    ),
                ),
                ("slavska_vodica", models.BooleanField(default=False)),
                ("vaskrsnja_vodica", models.BooleanField(default=False)),
                ("napomena", models.TextField(blank=True, null=True)),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.adresa",
                        verbose_name="адреса домаћинства",
                    ),
                ),
                (
                    "domacin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domacinstvo",
                        to="registar.osoba",
                        verbose_name="домаћин",
                    ),
                ),
                (
                    "slava",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.slava",
                        verbose_name="слава домаћинства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домаћинство",
                "verbose_name_plural": "Домаћинства",
                "db_table": "domacinstva",
            },
        ),
        migrations.CreateModel(
            name="Svestenik",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "uid",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="свестеник ид",
                    ),
                ),
                ("ime", models.CharField(verbose_name="име")),
                ("prezime", models.CharField(verbose_name="презиме")),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True, null=True, verbose_name="место рођења"
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "zvanje",
                    models.CharField(
                        choices=[
                            ("Патријарх Српски", "Патријарх Српски"),
                            ("Јереј", "Јереј"),
                            ("Протојереј", "Протојереј"),
                            ("Протојереј-ставрофор", "Протојереј-ставрофор"),
                            ("Протонамесник", "Протонамесник"),
                            ("Администратор", "Администратор"),
                            ("Митрополит", "Митрополит"),
                        ],
                        max_length=30,
                        verbose_name="звање",
                    ),
                ),
                (
                    "parohija",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.parohija",
                        verbose_name="парохија",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свештеник",
                "verbose_name_plural": "Свештеници",
                "db_table": "svestenici",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Krstenje",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "redni_broj_krstenja_tekuca_godina",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број крштења текућа година",
                    ),
                ),
                (
                    "krstenje_tekuca_godina",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="крштењe текућа година",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "broj",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="број",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                ("datum", models.DateField(verbose_name="датум")),
                (
                    "vreme",
                    models.TimeField(blank=True, null=True, verbose_name="време"),
                ),
                (
                    "mesto",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="место"
                    ),
                ),
                (
                    "adresa_deteta_grad",
                    models.CharField(max_length=255, verbose_name="адреса детета град"),
                ),
                (
                    "adresa_deteta_ulica",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="адреса детета улица",
                    ),
                ),
                (
                    "adresa_deteta_broj",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="адреса детета број",
                    ),
                ),
                (
                    "gradjansko_ime_deteta",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="грађанско име детета",
                    ),
                ),
                (
                    "adresa_oca_mesto",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="адреса оца место",
                    ),
                ),
                (
                    "adresa_majke_mesto",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="адреса мајке место",
                    ),
                ),
                (
                    "dete_rodjeno_zivo",
                    models.BooleanField(default=True, verbose_name="дете рођено живо"),
                ),
                (
                    "dete_po_redu_po_majci",
                    models.CharField(
                        blank=True, null=True, verbose_name="дете по реду (по мајци)"
                    ),
                ),
                ("dete_vanbracno", models.BooleanField(verbose_name="ванбрачно дете")),
                ("dete_blizanac", models.BooleanField(verbose_name="дете близанац")),
                (
                    "drugo_dete_blizanac_ime",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="име другог детета близанца",
                    ),
                ),
                (
                    "dete_sa_telesnom_manom",
                    models.BooleanField(verbose_name="дете са телесном маном"),
                ),
                (
                    "adresa_kuma_mesto",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="адреса кума место",
                    ),
                ),
                (
                    "mesto_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="место регистрације",
                    ),
                ),
                (
                    "datum_registracije",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум регистрације"
                    ),
                ),
                (
                    "maticni_broj",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="матични број",
                    ),
                ),
                (
                    "strana_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="страна регистрације",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, null=True, verbose_name="примедба"),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.hram",
                        verbose_name="храм",
                    ),
                ),
                (
                    "dete",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_dete",
                        to="registar.osoba",
                        verbose_name="дете",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_kum",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "majka",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_majka",
                        to="registar.osoba",
                        verbose_name="мајка",
                    ),
                ),
                (
                    "otac",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_otac",
                        to="registar.osoba",
                        verbose_name="отац",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="свештеник_крститељ",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Крштење",
                "verbose_name_plural": "Крштења",
                "db_table": "krstenja",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ulica",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "uid",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="назив")),
                (
                    "drzava",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registar.drzava",
                        verbose_name="држава",
                    ),
                ),
                (
                    "mesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registar.mesto",
                        verbose_name="место",
                    ),
                ),
                (
                    "opstina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registar.opstina",
                        verbose_name="општина",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Улица",
                "verbose_name_plural": "Улице",
                "db_table": "ulice",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="adresa",
            name="ulica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="registar.ulica",
                verbose_name="улица",
            ),
        ),
        migrations.CreateModel(
            name="Vencanje",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "godina_registracije",
                    models.IntegerField(
                        default=2000,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="година регистрације",
                    ),
                ),
                (
                    "redni_broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број венчања",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                (
                    "tekuci_broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="текући број",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум венчања"
                    ),
                ),
                (
                    "mesto_zenika",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="место женика",
                    ),
                ),
                (
                    "adresa_zenika",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="адреса женика",
                    ),
                ),
                (
                    "mesto_neveste",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="место невесте",
                    ),
                ),
                (
                    "adresa_neveste",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="адреса невесте",
                    ),
                ),
                (
                    "zenik_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду женика",
                    ),
                ),
                (
                    "nevesta_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду невесте",
                    ),
                ),
                (
                    "datum_ispita",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="датум испита",
                    ),
                ),
                (
                    "razresenje",
                    models.BooleanField(default=True, verbose_name="разрешење"),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, default="", verbose_name="примедба"),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.hram",
                        verbose_name="место венчања",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_kum",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "nevesta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_nevesta",
                        to="registar.osoba",
                        verbose_name="невеста",
                    ),
                ),
                (
                    "stari_svat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_stari_svat",
                        to="registar.osoba",
                        verbose_name="име старог свата",
                    ),
                ),
                (
                    "svekar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_svekar",
                        to="registar.osoba",
                        verbose_name="отац женика",
                    ),
                ),
                (
                    "svekrva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_svekrva",
                        to="registar.osoba",
                        verbose_name="мајка женика",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="свештеник_венчани",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
                (
                    "tast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_tast",
                        to="registar.osoba",
                        verbose_name="отац невесте",
                    ),
                ),
                (
                    "tasta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_tasta",
                        to="registar.osoba",
                        verbose_name="мајка невесте",
                    ),
                ),
                (
                    "zenik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_zenik",
                        to="registar.osoba",
                        verbose_name="женик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Венчање",
                "verbose_name_plural": "Венчања",
                "db_table": "vencanja",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ukucanin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Време креирања записа",
                        verbose_name="креирано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Време последње измене",
                        verbose_name="измењено",
                    ),
                ),
                (
                    "ime_ukucana",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uloga",
                    models.CharField(
                        choices=[
                            ("домаћин", "Домаћин"),
                            ("супружник", "Супружник/ка"),
                            ("дете", "Дете"),
                            ("рођак", "Рођак/сродник"),
                            ("остало", "Остало"),
                        ],
                        default="остало",
                        max_length=30,
                    ),
                ),
                (
                    "preminuo",
                    models.BooleanField(default=False, verbose_name="преминуо"),
                ),
                (
                    "domacinstvo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ukucani",
                        to="registar.domacinstvo",
                    ),
                ),
                (
                    "osoba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.osoba",
                        verbose_name="особа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Укућанин",
                "verbose_name_plural": "Укућани",
                "db_table": "ukucani",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("osoba__isnull", False)),
                        fields=("domacinstvo", "osoba"),
                        name="unique_osoba_per_domacinstvo",
                    )
                ],
            },
        ),
    ]
