# Generated by Django 4.2.16 on 2024-10-07 22:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broj', models.CharField(max_length=10, verbose_name='број')),
                ('dodatak', models.CharField(blank=True, max_length=10, null=True, verbose_name='додатак')),
                ('postkod', models.CharField(blank=True, max_length=10, null=True, verbose_name='поштански број')),
                ('primedba', models.TextField(blank=True, null=True, verbose_name='примедба')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адресе',
                'db_table': 'adrese',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CrkvenaOpstina',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'Црквена општина',
                'verbose_name_plural': 'Црквене општине',
                'db_table': 'crkvene_opstine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dan',
            fields=[
                ('dan', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='дан')),
            ],
            options={
                'verbose_name': 'Дан',
                'verbose_name_plural': 'Дани',
                'db_table': 'dani',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Domacinstvo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tel_fiksni', models.CharField(blank=True, max_length=255, null=True, verbose_name='тел. фиксни')),
                ('tel_mobilni', models.CharField(blank=True, max_length=255, null=True, verbose_name='тел. мобилни')),
                ('slavska_vodica', models.BooleanField(default=False, verbose_name='славска водица')),
                ('uskrsnja_vodica', models.BooleanField(default=False, verbose_name='ускршња водица')),
                ('primedba', models.TextField(blank=True, null=True, verbose_name='примедба')),
                ('adresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.adresa', verbose_name='адреса')),
            ],
            options={
                'verbose_name': 'Домаћинство',
                'verbose_name_plural': 'Домаћинства',
                'db_table': 'domacinstva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Drzava',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100, unique=True, verbose_name='назив')),
                ('izvorni_naziv', models.CharField(blank=True, max_length=100, null=True, verbose_name='изворни назив')),
                ('postkod_regex', models.CharField(blank=True, max_length=128, null=True, verbose_name='регекс поштанског броја')),
            ],
            options={
                'verbose_name': 'Држава',
                'verbose_name_plural': 'Државе',
                'db_table': 'drzave',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eparhija',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivo', models.CharField(choices=[('Епархија', 'Епархија'), ('Архиепископија', 'Архиепископија'), ('Митрополија', 'Митрополија')], default='Епархија', max_length=15, verbose_name='ниво')),
                ('naziv', models.CharField(max_length=100, verbose_name='назив')),
                ('sediste', models.CharField(max_length=100, verbose_name='седиште')),
            ],
            options={
                'verbose_name': 'Епархија',
                'verbose_name_plural': 'Епархије',
                'db_table': 'eparhije',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hram',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=200, verbose_name='назив')),
                ('adresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.adresa')),
            ],
            options={
                'verbose_name': 'Храм',
                'verbose_name_plural': 'Храмови',
                'db_table': 'hramovi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mesec',
            fields=[
                ('mesec', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='месец')),
                ('naziv', models.CharField(max_length=10, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'Месец',
                'verbose_name_plural': 'Месеци',
                'db_table': 'meseci',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'db_table': 'mesta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Narodnost',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=255, verbose_name='народност')),
            ],
            options={
                'verbose_name': 'Народност',
                'verbose_name_plural': 'Народности',
                'db_table': 'narodnosti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Opstina',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=100, verbose_name='назив')),
            ],
            options={
                'verbose_name': 'Општина',
                'verbose_name_plural': 'Општине',
                'db_table': 'opstine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parohija',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=200, verbose_name='назив')),
                ('crkvena_opstina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.crkvenaopstina', verbose_name='црквена општина')),
            ],
            options={
                'verbose_name': 'Парохија',
                'verbose_name_plural': 'Парохије',
                'db_table': 'parohije',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parohijan',
            fields=[
                ('uid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ime', models.CharField(verbose_name='име')),
                ('prezime', models.CharField(verbose_name='презиме')),
                ('mesto_rodjenja', models.CharField(verbose_name='место рођења')),
                ('datum_rodjenja', models.DateField(blank=True, null=True, verbose_name='датум рођења')),
                ('vreme_rodjenja', models.TimeField(blank=True, null=True, verbose_name='време рођења')),
                ('pol', models.CharField(choices=[('М', 'мушки'), ('Ж', 'женски')], verbose_name='пол')),
                ('devojacko_prezime', models.CharField(blank=True, verbose_name='девојачко презиме')),
                ('adresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.adresa', verbose_name='адреса')),
                ('narodnost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.narodnost', verbose_name='народност')),
            ],
            options={
                'verbose_name': 'Парохијан',
                'verbose_name_plural': 'Парохијани',
                'db_table': 'parohijani',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Svestenik',
            fields=[
                ('uid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='свестеник ид')),
                ('ime', models.CharField(verbose_name='име')),
                ('prezime', models.CharField(verbose_name='презиме')),
                ('mesto_rodjenja', models.CharField(verbose_name='место рођења')),
                ('datum_rodjenja', models.DateField(blank=True, null=True, verbose_name='датум рођења')),
                ('zvanje', models.CharField(choices=[('Патријарх Српски', 'Патријарх Српски'), ('Јереј', 'Јереј'), ('Протојереј', 'Протојереј'), ('Протојереј-ставрофор', 'Протојереј-ставрофор'), ('Протонамесник', 'Протонамесник'), ('Администратор', 'Администратор'), ('Митрополит', 'Митрополит')], max_length=30, verbose_name='звање')),
                ('parohija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.parohija', verbose_name='парохија')),
            ],
            options={
                'verbose_name': 'Свештеник',
                'verbose_name_plural': 'Свештеници',
                'db_table': 'svestenici',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Veroispovest',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=255, verbose_name='вероисповест')),
            ],
            options={
                'verbose_name': 'Вероисповест',
                'verbose_name_plural': 'Вероисповести',
                'db_table': 'veroispovesti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zanimanje',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sifra', models.CharField(verbose_name='шифра')),
                ('naziv', models.CharField(max_length=255, verbose_name='назив')),
                ('zenski_naziv', models.CharField(null=True, verbose_name='женски назив')),
            ],
            options={
                'verbose_name': 'Занимање',
                'verbose_name_plural': 'Занимања',
                'db_table': 'zanimanja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vencanje',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('knjiga', models.IntegerField(verbose_name='књига')),
                ('strana', models.IntegerField(verbose_name='страна')),
                ('tekuci_broj', models.IntegerField(verbose_name='текући број')),
                ('datum', models.DateField(verbose_name='датум венчања')),
                ('zenik_rb_brak', models.IntegerField(verbose_name='Рб. брак женика')),
                ('nevesta_rb_brak', models.IntegerField(verbose_name='Рб. брак невесте')),
                ('datum_ispita', models.DateField(verbose_name='датум испита')),
                ('parohija', models.CharField(verbose_name='свешт. парохија')),
                ('primedba', models.TextField(blank=True, verbose_name='примедба')),
                ('hram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.hram', verbose_name='место венчања')),
                ('kum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='венчани_кум', to='registar.parohijan', verbose_name='кум')),
                ('kuma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='венчана_кума', to='registar.parohijan', verbose_name='кума')),
                ('nevesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='невеста', to='registar.parohijan', verbose_name='невеста')),
                ('svekar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='свекар', to='registar.parohijan', verbose_name='свекар')),
                ('svekrva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='свекрва', to='registar.parohijan', verbose_name='свекрва')),
                ('svestenik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='свештеник_венчани', to='registar.svestenik', verbose_name='свештеник')),
                ('tast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='таст', to='registar.parohijan', verbose_name='таст')),
                ('tasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ташта', to='registar.parohijan', verbose_name='ташта')),
                ('zenik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='женик', to='registar.parohijan', verbose_name='женик')),
            ],
            options={
                'verbose_name': 'Венчање',
                'verbose_name_plural': 'Венчања',
                'db_table': 'vencanja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ulica',
            fields=[
                ('uid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('naziv', models.CharField(max_length=255, verbose_name='назив')),
                ('drzava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registar.drzava', verbose_name='држава')),
                ('mesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registar.mesto', verbose_name='место')),
                ('opstina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registar.opstina', verbose_name='општина')),
                ('svestenik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.svestenik', verbose_name='свештеник')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улице',
                'db_table': 'ulice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ukucanin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uloga', models.CharField(blank=True, max_length=255, verbose_name='улога')),
                ('domacinstvo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registar.domacinstvo', verbose_name='домаћинство')),
                ('parohijan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registar.parohijan', verbose_name='парохијан')),
            ],
            options={
                'verbose_name': 'Укућанин',
                'verbose_name_plural': 'Укућани',
                'db_table': 'ukucani',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slava',
            fields=[
                ('uid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('naziv', models.CharField(verbose_name='назив')),
                ('opsti_naziv', models.CharField(verbose_name='општи назив')),
                ('dan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.dan', verbose_name='дан')),
                ('mesec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.mesec', verbose_name='месец')),
            ],
            options={
                'verbose_name': 'Слава',
                'verbose_name_plural': 'Славе',
                'db_table': 'slave',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='parohijan',
            name='veroispovest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.veroispovest', verbose_name='вероисповест'),
        ),
        migrations.AddField(
            model_name='parohijan',
            name='zanimanje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.zanimanje', verbose_name='занимање'),
        ),
        migrations.CreateModel(
            name='Krstenje',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('knjiga', models.IntegerField(verbose_name='протоколарна књига')),
                ('strana', models.IntegerField(verbose_name='протоколарна страна')),
                ('tekuci_broj', models.IntegerField(verbose_name='текући број')),
                ('anagraf', models.IntegerField(blank=True, null=True, verbose_name='анаграф')),
                ('datum', models.DateField(verbose_name='датум крштења')),
                ('vreme', models.TimeField(verbose_name='време крштења')),
                ('dete_majci', models.IntegerField(verbose_name='дете по реду (по мајци)')),
                ('dete_bracno', models.BooleanField(verbose_name='брачно дете')),
                ('mana', models.BooleanField(verbose_name='мана')),
                ('primedba', models.TextField(blank=True, null=True, verbose_name='примедба')),
                ('blizanac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='близанац', to='registar.parohijan', verbose_name='близанац')),
                ('dete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='дете', to='registar.parohijan', verbose_name='дете')),
                ('hram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.hram', verbose_name='место крштења')),
                ('kum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='кум', to='registar.parohijan', verbose_name='кум')),
                ('majka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='мајка', to='registar.parohijan', verbose_name='мајка')),
                ('otac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='отац', to='registar.parohijan', verbose_name='отац')),
                ('svestenik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='свештеник_крститељ', to='registar.svestenik', verbose_name='свештеник')),
            ],
            options={
                'verbose_name': 'Крштењe',
                'verbose_name_plural': 'Крштења',
                'db_table': 'krstenja',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hram',
            name='parohija',
            field=models.ManyToManyField(to='registar.parohija', verbose_name='парохије'),
        ),
        migrations.AddField(
            model_name='domacinstvo',
            name='domacin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registar.parohijan', verbose_name='домаћин'),
        ),
        migrations.AddField(
            model_name='domacinstvo',
            name='slava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.slava', verbose_name='слава'),
        ),
        migrations.AddField(
            model_name='crkvenaopstina',
            name='eparhija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.eparhija', verbose_name='епархија'),
        ),
        migrations.AddField(
            model_name='adresa',
            name='ulica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registar.ulica', verbose_name='улица'),
        ),
    ]
