# Generated by Django 6.0.1 on 2026-06-14 13:39

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import model_utils.fields
import registar.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kalendar", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Adresa",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ulica",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="улица"
                    ),
                ),
                (
                    "broj",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="број"
                    ),
                ),
                (
                    "sprat",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="спрат"
                    ),
                ),
                (
                    "broj_stana",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="број стана"
                    ),
                ),
                (
                    "mesto",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="место",
                    ),
                ),
                (
                    "postkod",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="поштански број",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, default="", verbose_name="примедба"),
                ),
            ],
            options={
                "verbose_name": "Адреса",
                "verbose_name_plural": "Адресе",
                "db_table": "adrese",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Eparhija",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nivo",
                    models.CharField(
                        choices=[
                            ("Епархија", "Епархија"),
                            ("Архиепископија", "Архиепископија"),
                            ("Митрополија", "Митрополија"),
                        ],
                        default="Епархија",
                        max_length=15,
                        verbose_name="ниво",
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="назив")),
                ("sediste", models.CharField(max_length=100, verbose_name="седиште")),
            ],
            options={
                "verbose_name": "Епархија",
                "verbose_name_plural": "Епархије",
                "db_table": "eparhije",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Hram",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=200, verbose_name="назив")),
                (
                    "mesto",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="место"
                    ),
                ),
            ],
            options={
                "verbose_name": "Храм",
                "verbose_name_plural": "Храмови",
                "db_table": "hramovi",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Domacinstvo",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tel_fiksni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="мобилни телефон",
                    ),
                ),
                ("slavska_vodica", models.BooleanField(default=False)),
                ("vaskrsnja_vodica", models.BooleanField(default=False)),
                ("napomena", models.TextField(blank=True, null=True)),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.adresa",
                        verbose_name="адреса домаћинства",
                    ),
                ),
                (
                    "slava",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kalendar.slava",
                        verbose_name="слава домаћинства",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домаћинство",
                "verbose_name_plural": "Домаћинства",
                "db_table": "domacinstva",
                "ordering": [
                    "adresa__ulica",
                    "adresa__broj",
                    "domacin__prezime",
                    "domacin__ime",
                ],
            },
        ),
        migrations.CreateModel(
            name="CrkvenaOpstina",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=100, verbose_name="назив")),
                (
                    "eparhija",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.eparhija",
                        verbose_name="епархија",
                    ),
                ),
            ],
            options={
                "verbose_name": "Црквена општина",
                "verbose_name_plural": "Црквене општине",
                "db_table": "crkvene_opstine",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Narodnost",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=255, verbose_name="народност")),
            ],
            options={
                "verbose_name": "Народност",
                "verbose_name_plural": "Народности",
                "db_table": "narodnosti",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("naziv"),
                        name="narodnost_naziv_ci_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Osoba",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "ime",
                    models.CharField(db_index=True, max_length=100, verbose_name="име"),
                ),
                (
                    "prezime",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="презиме"
                    ),
                ),
                (
                    "devojacko_prezime",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="девојачко презиме",
                    ),
                ),
                (
                    "gradjansko_ime",
                    models.CharField(
                        blank=True,
                        help_text="Грађанско (световно) име ако се разликује од крштеног",
                        max_length=100,
                        null=True,
                        verbose_name="грађанско име",
                    ),
                ),
                (
                    "parohijan",
                    models.BooleanField(
                        default=False,
                        help_text="Да ли је особа парохијанин",
                        verbose_name="парохијан",
                    ),
                ),
                (
                    "tel_fiksni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="мобилни телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="имејл"
                    ),
                ),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="место рођења",
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "vreme_rodjenja",
                    models.TimeField(
                        blank=True, null=True, verbose_name="време рођења"
                    ),
                ),
                (
                    "pol",
                    models.CharField(
                        blank=True,
                        choices=[("М", "мушки"), ("Ж", "женски")],
                        db_index=True,
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.adresa",
                        verbose_name="адреса",
                    ),
                ),
                (
                    "narodnost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.narodnost",
                        verbose_name="народност",
                    ),
                ),
            ],
            options={
                "verbose_name": "Особа",
                "verbose_name_plural": "Особе",
                "db_table": "osobe",
                "ordering": ["prezime", "ime"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HistoricalUkucanin",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "ime_ukucana",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uloga",
                    models.CharField(
                        choices=[
                            ("домаћин", "Домаћин"),
                            ("супружник", "Супружник/ка"),
                            ("дете", "Дете"),
                            ("рођак", "Рођак/сродник"),
                            ("остало", "Остало"),
                        ],
                        default="остало",
                        max_length=30,
                    ),
                ),
                (
                    "preminuo",
                    models.BooleanField(default=False, verbose_name="преминуо"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "domacinstvo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.domacinstvo",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "osoba",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="особа",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Укућанин",
                "verbose_name_plural": "historical Укућани",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDomacinstvo",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "tel_fiksni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="мобилни телефон",
                    ),
                ),
                ("slavska_vodica", models.BooleanField(default=False)),
                ("vaskrsnja_vodica", models.BooleanField(default=False)),
                ("napomena", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.adresa",
                        verbose_name="адреса домаћинства",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slava",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="kalendar.slava",
                        verbose_name="слава домаћинства",
                    ),
                ),
                (
                    "domacin",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="домаћин",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Домаћинство",
                "verbose_name_plural": "historical Домаћинства",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="domacinstvo",
            name="domacin",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domacinstvo",
                to="registar.osoba",
                verbose_name="домаћин",
            ),
        ),
        migrations.CreateModel(
            name="Parohija",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("naziv", models.CharField(max_length=200, verbose_name="назив")),
                (
                    "crkvena_opstina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.crkvenaopstina",
                        verbose_name="црквена општина",
                    ),
                ),
            ],
            options={
                "verbose_name": "Парохија",
                "verbose_name_plural": "Парохије",
                "db_table": "parohije",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HistoricalSvestenik",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="свестеник ид",
                    ),
                ),
                ("ime", models.CharField(max_length=100, verbose_name="име")),
                ("prezime", models.CharField(max_length=100, verbose_name="презиме")),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="место рођења",
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "zvanje",
                    models.CharField(
                        choices=[
                            ("патријарх српски", "патријарх српски"),
                            ("јереј", "јереј"),
                            ("протојереј", "протојереј"),
                            ("протојереј-ставрофор", "протојереј-ставрофор"),
                            ("протонамесник", "протонамесник"),
                            ("администратор", "администратор"),
                            ("митрополит", "митрополит"),
                        ],
                        max_length=30,
                        verbose_name="звање",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.adresa",
                        verbose_name="адреса",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Налог којим се свештеник пријављује; потпис у подножју преписа (издавалац) узима свештеника везаног за пријављеног корисника.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кориснички налог",
                    ),
                ),
                (
                    "parohija",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.parohija",
                        verbose_name="парохија",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Свештеник",
                "verbose_name_plural": "historical Свештеници",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Svestenik",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="свестеник ид",
                    ),
                ),
                ("ime", models.CharField(max_length=100, verbose_name="име")),
                ("prezime", models.CharField(max_length=100, verbose_name="презиме")),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="место рођења",
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "zvanje",
                    models.CharField(
                        choices=[
                            ("патријарх српски", "патријарх српски"),
                            ("јереј", "јереј"),
                            ("протојереј", "протојереј"),
                            ("протојереј-ставрофор", "протојереј-ставрофор"),
                            ("протонамесник", "протонамесник"),
                            ("администратор", "администратор"),
                            ("митрополит", "митрополит"),
                        ],
                        max_length=30,
                        verbose_name="звање",
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="registar.adresa",
                        verbose_name="адреса",
                    ),
                ),
                (
                    "parohija",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.parohija",
                        verbose_name="парохија",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Налог којим се свештеник пријављује; потпис у подножју преписа (издавалац) узима свештеника везаног за пријављеног корисника.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="svestenik",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кориснички налог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свештеник",
                "verbose_name_plural": "Свештеници",
                "db_table": "svestenici",
                "ordering": ["prezime", "ime"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Krstenje",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "godina_registracije",
                    models.IntegerField(
                        db_index=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="година регистрације",
                    ),
                ),
                (
                    "redni_broj",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број крштења",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                (
                    "broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="текући број",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="датум"
                    ),
                ),
                (
                    "vreme",
                    models.TimeField(blank=True, null=True, verbose_name="време"),
                ),
                (
                    "zivorodjeno",
                    models.BooleanField(default=True, verbose_name="живорођено"),
                ),
                (
                    "po_redu",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Колико је дете по реду рођења мајци (1 = прво). Празно = није уписано.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="по реду мајци",
                    ),
                ),
                (
                    "vanbracno",
                    models.BooleanField(default=False, verbose_name="ванбрачно"),
                ),
                (
                    "blizanac",
                    models.BooleanField(default=False, verbose_name="близанац"),
                ),
                (
                    "ime_blizanca",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="име близанца",
                    ),
                ),
                (
                    "telesna_mana",
                    models.BooleanField(default=False, verbose_name="телесна мана"),
                ),
                (
                    "mesto_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="место регистрације",
                    ),
                ),
                (
                    "datum_registracije",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум регистрације"
                    ),
                ),
                (
                    "maticni_broj",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="матични број",
                    ),
                ),
                (
                    "strana_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="страна регистрације",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, null=True, verbose_name="примедба"),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.hram",
                        verbose_name="храм",
                    ),
                ),
                (
                    "dete",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_dete",
                        to="registar.osoba",
                        verbose_name="дете",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_kum",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "majka",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_majka",
                        to="registar.osoba",
                        verbose_name="мајка",
                    ),
                ),
                (
                    "otac",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="krstenja_kao_otac",
                        to="registar.osoba",
                        verbose_name="отац",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="свештеник_крститељ",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Крштење",
                "verbose_name_plural": "Крштења",
                "db_table": "krstenja",
                "ordering": ["-datum"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HistoricalVencanje",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "godina_registracije",
                    models.IntegerField(
                        db_index=True,
                        default=2000,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="година регистрације",
                    ),
                ),
                (
                    "redni_broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број венчања",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                (
                    "broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="текући број",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="датум"
                    ),
                ),
                (
                    "zenik_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду женика",
                    ),
                ),
                (
                    "nevesta_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду невесте",
                    ),
                ),
                (
                    "datum_ispita",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="датум испита",
                    ),
                ),
                (
                    "razresenje",
                    models.BooleanField(default=True, verbose_name="разрешење"),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, default="", verbose_name="примедба"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.hram",
                        verbose_name="место венчања",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "nevesta",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="невеста",
                    ),
                ),
                (
                    "stari_svat",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="име старог свата",
                    ),
                ),
                (
                    "svekar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="отац женика",
                    ),
                ),
                (
                    "svekrva",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="мајка женика",
                    ),
                ),
                (
                    "tast",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="отац невесте",
                    ),
                ),
                (
                    "tasta",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="мајка невесте",
                    ),
                ),
                (
                    "zenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="женик",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Венчање",
                "verbose_name_plural": "historical Венчања",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalKrstenje",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "godina_registracije",
                    models.IntegerField(
                        db_index=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="година регистрације",
                    ),
                ),
                (
                    "redni_broj",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број крштења",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                (
                    "broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="текући број",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="датум"
                    ),
                ),
                (
                    "vreme",
                    models.TimeField(blank=True, null=True, verbose_name="време"),
                ),
                (
                    "zivorodjeno",
                    models.BooleanField(default=True, verbose_name="живорођено"),
                ),
                (
                    "po_redu",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Колико је дете по реду рођења мајци (1 = прво). Празно = није уписано.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="по реду мајци",
                    ),
                ),
                (
                    "vanbracno",
                    models.BooleanField(default=False, verbose_name="ванбрачно"),
                ),
                (
                    "blizanac",
                    models.BooleanField(default=False, verbose_name="близанац"),
                ),
                (
                    "ime_blizanca",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="име близанца",
                    ),
                ),
                (
                    "telesna_mana",
                    models.BooleanField(default=False, verbose_name="телесна мана"),
                ),
                (
                    "mesto_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="место регистрације",
                    ),
                ),
                (
                    "datum_registracije",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум регистрације"
                    ),
                ),
                (
                    "maticni_broj",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="матични број",
                    ),
                ),
                (
                    "strana_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="страна регистрације",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, null=True, verbose_name="примедба"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.hram",
                        verbose_name="храм",
                    ),
                ),
                (
                    "dete",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="дете",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "majka",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="мајка",
                    ),
                ),
                (
                    "otac",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="отац",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Крштење",
                "verbose_name_plural": "historical Крштења",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAdresa",
            fields=[
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "ulica",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="улица"
                    ),
                ),
                (
                    "broj",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="број"
                    ),
                ),
                (
                    "sprat",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="спрат"
                    ),
                ),
                (
                    "broj_stana",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="број стана"
                    ),
                ),
                (
                    "mesto",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="место",
                    ),
                ),
                (
                    "postkod",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="поштански број",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, default="", verbose_name="примедба"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Свештеник задужен за ову улицу (за васкршњу водицу).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.svestenik",
                        verbose_name="свештеник (улица)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Адреса",
                "verbose_name_plural": "historical Адресе",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="adresa",
            name="svestenik",
            field=models.ForeignKey(
                blank=True,
                help_text="Свештеник задужен за ову улицу (за васкршњу водицу).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adrese",
                to="registar.svestenik",
                verbose_name="свештеник (улица)",
            ),
        ),
        migrations.CreateModel(
            name="Ukucanin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "ime_ukucana",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uloga",
                    models.CharField(
                        choices=[
                            ("домаћин", "Домаћин"),
                            ("супружник", "Супружник/ка"),
                            ("дете", "Дете"),
                            ("рођак", "Рођак/сродник"),
                            ("остало", "Остало"),
                        ],
                        default="остало",
                        max_length=30,
                    ),
                ),
                (
                    "preminuo",
                    models.BooleanField(default=False, verbose_name="преминуо"),
                ),
                (
                    "domacinstvo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ukucani",
                        to="registar.domacinstvo",
                    ),
                ),
                (
                    "osoba",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.osoba",
                        verbose_name="особа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Укућанин",
                "verbose_name_plural": "Укућани",
                "db_table": "ukucani",
            },
        ),
        migrations.CreateModel(
            name="Vencanje",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "godina_registracije",
                    models.IntegerField(
                        db_index=True,
                        default=2000,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="година регистрације",
                    ),
                ),
                (
                    "redni_broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број венчања",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                (
                    "broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="текући број",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="датум"
                    ),
                ),
                (
                    "zenik_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду женика",
                    ),
                ),
                (
                    "nevesta_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду невесте",
                    ),
                ),
                (
                    "datum_ispita",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="датум испита",
                    ),
                ),
                (
                    "razresenje",
                    models.BooleanField(default=True, verbose_name="разрешење"),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, default="", verbose_name="примедба"),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="registar.hram",
                        verbose_name="место венчања",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_kum",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "nevesta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_nevesta",
                        to="registar.osoba",
                        verbose_name="невеста",
                    ),
                ),
                (
                    "stari_svat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_stari_svat",
                        to="registar.osoba",
                        verbose_name="име старог свата",
                    ),
                ),
                (
                    "svekar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_svekar",
                        to="registar.osoba",
                        verbose_name="отац женика",
                    ),
                ),
                (
                    "svekrva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_svekrva",
                        to="registar.osoba",
                        verbose_name="мајка женика",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="свештеник_венчани",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
                (
                    "tast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_tast",
                        to="registar.osoba",
                        verbose_name="отац невесте",
                    ),
                ),
                (
                    "tasta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_tasta",
                        to="registar.osoba",
                        verbose_name="мајка невесте",
                    ),
                ),
                (
                    "zenik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vencanja_kao_zenik",
                        to="registar.osoba",
                        verbose_name="женик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Венчање",
                "verbose_name_plural": "Венчања",
                "db_table": "vencanja",
                "ordering": ["-datum"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Veroispovest",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "naziv",
                    models.CharField(max_length=255, verbose_name="вероисповест"),
                ),
            ],
            options={
                "verbose_name": "Вероисповест",
                "verbose_name_plural": "Вероисповести",
                "db_table": "veroispovesti",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("naziv"),
                        name="veroispovest_naziv_ci_uniq",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="osoba",
            name="veroispovest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registar.veroispovest",
                verbose_name="вероисповест",
            ),
        ),
        migrations.CreateModel(
            name="Zanimanje",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sifra", models.CharField(max_length=50, verbose_name="шифра")),
                ("naziv", models.CharField(max_length=255, verbose_name="назив")),
                (
                    "zenski_naziv",
                    models.CharField(
                        max_length=255, null=True, verbose_name="женски назив"
                    ),
                ),
            ],
            options={
                "verbose_name": "Занимање",
                "verbose_name_plural": "Занимања",
                "db_table": "zanimanja",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("naziv"),
                        name="zanimanje_naziv_ci_uniq",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="osoba",
            name="zanimanje",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registar.zanimanje",
                verbose_name="занимање",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOsoba",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uid", models.IntegerField(blank=True, db_index=True, editable=False)),
                (
                    "ime",
                    models.CharField(db_index=True, max_length=100, verbose_name="име"),
                ),
                (
                    "prezime",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="презиме"
                    ),
                ),
                (
                    "devojacko_prezime",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="девојачко презиме",
                    ),
                ),
                (
                    "gradjansko_ime",
                    models.CharField(
                        blank=True,
                        help_text="Грађанско (световно) име ако се разликује од крштеног",
                        max_length=100,
                        null=True,
                        verbose_name="грађанско име",
                    ),
                ),
                (
                    "parohijan",
                    models.BooleanField(
                        default=False,
                        help_text="Да ли је особа парохијанин",
                        verbose_name="парохијан",
                    ),
                ),
                (
                    "tel_fiksni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    registar.fields.TenantPhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="мобилни телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="имејл"
                    ),
                ),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="место рођења",
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "vreme_rodjenja",
                    models.TimeField(
                        blank=True, null=True, verbose_name="време рођења"
                    ),
                ),
                (
                    "pol",
                    models.CharField(
                        blank=True,
                        choices=[("М", "мушки"), ("Ж", "женски")],
                        db_index=True,
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.adresa",
                        verbose_name="адреса",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "narodnost",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.narodnost",
                        verbose_name="народност",
                    ),
                ),
                (
                    "veroispovest",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.veroispovest",
                        verbose_name="вероисповест",
                    ),
                ),
                (
                    "zanimanje",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.zanimanje",
                        verbose_name="занимање",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Особа",
                "verbose_name_plural": "historical Особе",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="svestenik",
            index=models.Index(fields=["created"], name="svestenik_created_idx"),
        ),
        migrations.AddIndex(
            model_name="krstenje",
            index=models.Index(
                fields=["godina_registracije", "knjiga", "strana", "broj"],
                name="krstenje_protocol_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="krstenje",
            constraint=models.UniqueConstraint(
                fields=("godina_registracije", "redni_broj"),
                name="krstenje_god_redni_uniq",
                violation_error_message="Крштење са овим редним бројем у датој години регистрације већ постоји.",
            ),
        ),
        migrations.AddIndex(
            model_name="adresa",
            index=models.Index(fields=["ulica", "broj"], name="adresa_ulica_broj_idx"),
        ),
        migrations.AddConstraint(
            model_name="adresa",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("ulica"),
                django.db.models.functions.text.Lower("broj"),
                django.db.models.functions.text.Lower("broj_stana"),
                django.db.models.functions.text.Lower("mesto"),
                name="unique_adresa_normalized",
            ),
        ),
        migrations.AddConstraint(
            model_name="ukucanin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("osoba__isnull", False)),
                fields=("domacinstvo", "osoba"),
                name="unique_osoba_per_domacinstvo",
            ),
        ),
        migrations.AddIndex(
            model_name="vencanje",
            index=models.Index(
                fields=["godina_registracije", "knjiga", "strana", "broj"],
                name="vencanje_protocol_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="vencanje",
            constraint=models.UniqueConstraint(
                fields=("godina_registracije", "redni_broj"),
                name="vencanje_god_redni_uniq",
                violation_error_message="Венчање са овим редним бројем у датој години регистрације већ постоји.",
            ),
        ),
        migrations.AddIndex(
            model_name="osoba",
            index=models.Index(fields=["created"], name="osoba_created_idx"),
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS osoba_ime_trgm_idx ON osobe USING gin (ime public.gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS osoba_ime_trgm_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS osoba_prezime_trgm_idx ON osobe USING gin (prezime public.gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS osoba_prezime_trgm_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS adresa_ulica_trgm_idx ON adrese USING gin (ulica public.gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS adresa_ulica_trgm_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS adresa_mesto_trgm_idx ON adrese USING gin (mesto public.gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS adresa_mesto_trgm_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS hram_naziv_trgm_idx ON hramovi USING gin (naziv public.gin_trgm_ops);",
            reverse_sql="DROP INDEX IF EXISTS hram_naziv_trgm_idx;",
        ),
    ]
