# Generated by Django 5.1.13 on 2025-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slava',
            name='uid',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
