# Generated by Django 6.0.1 on 2026-05-16 14:08

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ulica",
            name="drzava",
        ),
        migrations.RemoveField(
            model_name="ulica",
            name="mesto",
        ),
        migrations.RemoveField(
            model_name="ulica",
            name="opstina",
        ),
        migrations.RemoveField(
            model_name="ulica",
            name="svestenik",
        ),
        migrations.AlterField(
            model_name="adresa",
            name="ulica",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="улица"
            ),
        ),
        migrations.AlterModelOptions(
            name="osoba",
            options={
                "managed": True,
                "ordering": ["prezime", "ime"],
                "verbose_name": "Особа",
                "verbose_name_plural": "Особе",
            },
        ),
        migrations.RemoveField(
            model_name="adresa",
            name="dodatak",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="adresa_deteta_broj",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="adresa_deteta_grad",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="adresa_deteta_ulica",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="adresa_kuma_mesto",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="adresa_majke_mesto",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="adresa_oca_mesto",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="gradjansko_ime_deteta",
        ),
        migrations.RemoveField(
            model_name="krstenje",
            name="mesto",
        ),
        migrations.RemoveField(
            model_name="osoba",
            name="slava",
        ),
        migrations.RemoveField(
            model_name="osoba",
            name="slavska_vodica",
        ),
        migrations.RemoveField(
            model_name="osoba",
            name="uskrsnja_vodica",
        ),
        migrations.RemoveField(
            model_name="vencanje",
            name="adresa_neveste",
        ),
        migrations.RemoveField(
            model_name="vencanje",
            name="adresa_zenika",
        ),
        migrations.RemoveField(
            model_name="vencanje",
            name="mesto_neveste",
        ),
        migrations.RemoveField(
            model_name="vencanje",
            name="mesto_zenika",
        ),
        migrations.AddField(
            model_name="adresa",
            name="mesto",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="место"
            ),
        ),
        migrations.AddField(
            model_name="hram",
            name="mesto",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="место"
            ),
        ),
        migrations.AddField(
            model_name="osoba",
            name="gradjansko_ime",
            field=models.CharField(
                blank=True,
                help_text="Грађанско (световно) име ако се разликује од крштеног",
                max_length=100,
                null=True,
                verbose_name="грађанско име",
            ),
        ),
        migrations.AlterField(
            model_name="adresa",
            name="broj",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="број"
            ),
        ),
        migrations.AlterField(
            model_name="adresa",
            name="broj_stana",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="број стана"
            ),
        ),
        migrations.AlterField(
            model_name="adresa",
            name="postkod",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="поштански број"
            ),
        ),
        migrations.AlterField(
            model_name="adresa",
            name="primedba",
            field=models.TextField(blank=True, default="", verbose_name="примедба"),
        ),
        migrations.AlterField(
            model_name="adresa",
            name="sprat",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="спрат"
            ),
        ),
        migrations.AlterField(
            model_name="krstenje",
            name="datum",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="датум"
            ),
        ),
        migrations.AlterField(
            model_name="krstenje",
            name="godina_registracije",
            field=models.IntegerField(
                db_index=True,
                validators=[django.core.validators.MinValueValidator(1900)],
                verbose_name="година регистрације",
            ),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="ime",
            field=models.CharField(db_index=True, max_length=100, verbose_name="име"),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="narodnost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registar.narodnost",
                verbose_name="народност",
            ),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="prezime",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="презиме"
            ),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="veroispovest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registar.veroispovest",
                verbose_name="вероисповест",
            ),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="zanimanje",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registar.zanimanje",
                verbose_name="занимање",
            ),
        ),
        migrations.AlterField(
            model_name="slava",
            name="dan",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="дан",
            ),
        ),
        migrations.AlterField(
            model_name="slava",
            name="mesec",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="месец",
            ),
        ),
        migrations.AlterField(
            model_name="vencanje",
            name="datum",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="датум"
            ),
        ),
        migrations.AlterField(
            model_name="vencanje",
            name="godina_registracije",
            field=models.IntegerField(
                db_index=True,
                default=2000,
                validators=[django.core.validators.MinValueValidator(1900)],
                verbose_name="година регистрације",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalKrstenje",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "godina_registracije",
                    models.IntegerField(
                        db_index=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="година регистрације",
                    ),
                ),
                (
                    "redni_broj",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број крштења",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                (
                    "broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="текући број",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="датум"
                    ),
                ),
                (
                    "vreme",
                    models.TimeField(blank=True, null=True, verbose_name="време"),
                ),
                (
                    "dete_rodjeno_zivo",
                    models.BooleanField(default=True, verbose_name="дете рођено живо"),
                ),
                (
                    "dete_po_redu_po_majci",
                    models.CharField(
                        blank=True, null=True, verbose_name="дете по реду (по мајци)"
                    ),
                ),
                ("dete_vanbracno", models.BooleanField(verbose_name="ванбрачно дете")),
                ("dete_blizanac", models.BooleanField(verbose_name="дете близанац")),
                (
                    "drugo_dete_blizanac_ime",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="име другог детета близанца",
                    ),
                ),
                (
                    "dete_sa_telesnom_manom",
                    models.BooleanField(verbose_name="дете са телесном маном"),
                ),
                (
                    "mesto_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="место регистрације",
                    ),
                ),
                (
                    "datum_registracije",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум регистрације"
                    ),
                ),
                (
                    "maticni_broj",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="матични број",
                    ),
                ),
                (
                    "strana_registracije",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="страна регистрације",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, null=True, verbose_name="примедба"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dete",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="дете",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.hram",
                        verbose_name="храм",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "majka",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="мајка",
                    ),
                ),
                (
                    "otac",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="отац",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Крштење",
                "verbose_name_plural": "historical Крштења",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOsoba",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uid", models.IntegerField(blank=True, db_index=True, editable=False)),
                (
                    "ime",
                    models.CharField(db_index=True, max_length=100, verbose_name="име"),
                ),
                (
                    "prezime",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="презиме"
                    ),
                ),
                (
                    "devojacko_prezime",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="девојачко презиме",
                    ),
                ),
                (
                    "gradjansko_ime",
                    models.CharField(
                        blank=True,
                        help_text="Грађанско (световно) име ако се разликује од крштеног",
                        max_length=100,
                        null=True,
                        verbose_name="грађанско име",
                    ),
                ),
                (
                    "parohijan",
                    models.BooleanField(
                        default=False,
                        help_text="Да ли је особа парохијанин",
                        verbose_name="парохијан",
                    ),
                ),
                (
                    "tel_fiksni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="мобилни телефон",
                    ),
                ),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="место рођења",
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "vreme_rodjenja",
                    models.TimeField(
                        blank=True, null=True, verbose_name="време рођења"
                    ),
                ),
                (
                    "pol",
                    models.CharField(
                        blank=True,
                        choices=[("М", "мушки"), ("Ж", "женски")],
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.adresa",
                        verbose_name="адреса",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "narodnost",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.narodnost",
                        verbose_name="народност",
                    ),
                ),
                (
                    "veroispovest",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.veroispovest",
                        verbose_name="вероисповест",
                    ),
                ),
                (
                    "zanimanje",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.zanimanje",
                        verbose_name="занимање",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Особа",
                "verbose_name_plural": "historical Особе",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVencanje",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "godina_registracije",
                    models.IntegerField(
                        db_index=True,
                        default=2000,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="година регистрације",
                    ),
                ),
                (
                    "redni_broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="редни број венчања",
                    ),
                ),
                (
                    "knjiga",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="књига",
                    ),
                ),
                (
                    "strana",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="страна",
                    ),
                ),
                (
                    "broj",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="текући број",
                    ),
                ),
                (
                    "datum",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="датум"
                    ),
                ),
                (
                    "zenik_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду женика",
                    ),
                ),
                (
                    "nevesta_rb_brak",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="брак по реду невесте",
                    ),
                ),
                (
                    "datum_ispita",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="датум испита",
                    ),
                ),
                (
                    "razresenje",
                    models.BooleanField(default=True, verbose_name="разрешење"),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, default="", verbose_name="примедба"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hram",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.hram",
                        verbose_name="место венчања",
                    ),
                ),
                (
                    "kum",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="кум",
                    ),
                ),
                (
                    "nevesta",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="невеста",
                    ),
                ),
                (
                    "stari_svat",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="име старог свата",
                    ),
                ),
                (
                    "svekar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="отац женика",
                    ),
                ),
                (
                    "svekrva",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="мајка женика",
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.svestenik",
                        verbose_name="свештеник",
                    ),
                ),
                (
                    "tast",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="отац невесте",
                    ),
                ),
                (
                    "tasta",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="мајка невесте",
                    ),
                ),
                (
                    "zenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="женик",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Венчање",
                "verbose_name_plural": "historical Венчања",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="Drzava",
        ),
        migrations.DeleteModel(
            name="Mesto",
        ),
        migrations.DeleteModel(
            name="Opstina",
        ),
        migrations.DeleteModel(
            name="Ulica",
        ),
    ]
