# Generated by Django 6.0.1 on 2026-06-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvencanje",
            name="datum_ispita",
            field=models.DateField(blank=True, null=True, verbose_name="датум испита"),
        ),
        migrations.AlterField(
            model_name="vencanje",
            name="datum_ispita",
            field=models.DateField(blank=True, null=True, verbose_name="датум испита"),
        ),
    ]
