# Generated by Django 6.0.1 on 2026-06-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0002_alter_krstenje_hram_alter_krstenje_svestenik"),
    ]

    operations = [
        migrations.AddField(
            model_name="adresa",
            name="svestenik",
            field=models.ForeignKey(
                blank=True,
                help_text="Свештеник задужен за ову улицу (за васкршњу водицу).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adrese",
                to="registar.svestenik",
                verbose_name="свештеник (улица)",
            ),
        ),
        migrations.AlterField(
            model_name="svestenik",
            name="adresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="registar.adresa",
                verbose_name="адреса",
            ),
        ),
    ]
