# Generated by Django 6.0.1 on 2026-05-16 22:52

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0002_remove_ulica_drzava_remove_ulica_mesto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDomacinstvo",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "tel_fiksni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="фиксни телефон",
                    ),
                ),
                (
                    "tel_mobilni",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RS",
                        verbose_name="мобилни телефон",
                    ),
                ),
                ("slavska_vodica", models.BooleanField(default=False)),
                ("vaskrsnja_vodica", models.BooleanField(default=False)),
                ("napomena", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "adresa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.adresa",
                        verbose_name="адреса домаћинства",
                    ),
                ),
                (
                    "domacin",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="домаћин",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slava",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.slava",
                        verbose_name="слава домаћинства",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Домаћинство",
                "verbose_name_plural": "historical Домаћинства",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSvestenik",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uid",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="свестеник ид",
                    ),
                ),
                ("ime", models.CharField(verbose_name="име")),
                ("prezime", models.CharField(verbose_name="презиме")),
                (
                    "mesto_rodjenja",
                    models.CharField(
                        blank=True, null=True, verbose_name="место рођења"
                    ),
                ),
                (
                    "datum_rodjenja",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="датум рођења"
                    ),
                ),
                (
                    "zvanje",
                    models.CharField(
                        choices=[
                            ("Патријарх Српски", "Патријарх Српски"),
                            ("Јереј", "Јереј"),
                            ("Протојереј", "Протојереј"),
                            ("Протојереј-ставрофор", "Протојереј-ставрофор"),
                            ("Протонамесник", "Протонамесник"),
                            ("Администратор", "Администратор"),
                            ("Митрополит", "Митрополит"),
                        ],
                        max_length=30,
                        verbose_name="звање",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parohija",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.parohija",
                        verbose_name="парохија",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Свештеник",
                "verbose_name_plural": "historical Свештеници",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
