# Generated by Django 6.0.1 on 2026-06-04 08:02
# Hand-augmented with a data migration: the po_redu column historically held
# either ordinal WORDS (прво…десето) or numeric strings ("1"). We convert
# everything to plain digit strings (NULLing anything unparseable) BEFORE the
# varchar -> smallint AlterField, so the implicit ``USING po_redu::smallint``
# cast can never fail. Display back as words is handled by the redni_rec filter.

from django.db import migrations, models

WORD_TO_NUM = {
    "прво": 1, "друго": 2, "треће": 3, "четврто": 4, "пето": 5,
    "шесто": 6, "седмо": 7, "осмо": 8, "девето": 9, "десето": 10,
    "једанаесто": 11, "дванаесто": 12, "тринаесто": 13, "четрнаесто": 14,
    "петнаесто": 15, "шеснаесто": 16, "седамнаесто": 17, "осамнаесто": 18,
    "деветнаесто": 19, "двадесето": 20,
}


def _convert(model):
    """Words -> digit strings; anything not a plain digit string -> NULL."""
    for word, num in WORD_TO_NUM.items():
        model.objects.filter(po_redu=word).update(po_redu=str(num))
    model.objects.exclude(po_redu__regex=r"^[0-9]+$").update(po_redu=None)


def _revert(model):
    """Digit strings -> words (best effort, for migration rollback)."""
    for word, num in WORD_TO_NUM.items():
        model.objects.filter(po_redu=str(num)).update(po_redu=word)


def words_to_int(apps, schema_editor):
    _convert(apps.get_model("registar", "Krstenje"))
    _convert(apps.get_model("registar", "HistoricalKrstenje"))


def int_to_words(apps, schema_editor):
    _revert(apps.get_model("registar", "Krstenje"))
    _revert(apps.get_model("registar", "HistoricalKrstenje"))


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0002_pg_trgm_search_indexes'),
    ]

    operations = [
        migrations.RunPython(words_to_int, int_to_words),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='po_redu',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Број (нпр. 1, 2, 3…) — приказује се речима', null=True, verbose_name='по реду мајци'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='po_redu',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Број (нпр. 1, 2, 3…) — приказује се речима', null=True, verbose_name='по реду мајци'),
        ),
    ]
