# Generated by Django 6.0.1 on 2026-06-04 08:10
# Hand-augmented: po_redu is 1-based ("по реду мајци") — never 0 or NULL.
# Backfill any NULL/0 to 1 before enforcing NOT NULL + default=1.

import django.core.validators
from django.db import migrations, models


def backfill_po_redu(apps, schema_editor):
    for name in ("Krstenje", "HistoricalKrstenje"):
        model = apps.get_model("registar", name)
        model.objects.filter(po_redu__isnull=True).update(po_redu=1)
        model.objects.filter(po_redu=0).update(po_redu=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0003_alter_historicalkrstenje_po_redu_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_po_redu, noop),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='po_redu',
            field=models.PositiveSmallIntegerField(default=1, help_text='Колико је дете по реду рођења мајци (1 = прво) — приказује се речима', validators=[django.core.validators.MinValueValidator(1)], verbose_name='по реду мајци'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='po_redu',
            field=models.PositiveSmallIntegerField(default=1, help_text='Колико је дете по реду рођења мајци (1 = прво) — приказује се речима', validators=[django.core.validators.MinValueValidator(1)], verbose_name='по реду мајци'),
        ),
    ]
