# Generated by Django 6.0.1 on 2026-05-17 15:30

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0003_historicaldomacinstvo_historicalsvestenik"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="adresa",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("ulica"),
                django.db.models.functions.text.Lower("broj"),
                django.db.models.functions.text.Lower("broj_stana"),
                django.db.models.functions.text.Lower("mesto"),
                name="unique_adresa_normalized",
            ),
        ),
    ]
