# Generated by Django 6.0.1 on 2026-07-13 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0004_alter_historicaladresa_history_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="svestenik",
            name="user",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                help_text="Налог којим се свештеник пријављује; потпис у подножју преписа (издавалац) узима свештеника везаног за пријављеног корисника.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="svestenik",
                to=settings.AUTH_USER_MODEL,
                verbose_name="кориснички налог",
            ),
        ),
    ]
