# Generated by Django 5.1.13 on 2025-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0004_remove_dan_mesec_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="slava",
            name="offset_dani",
            field=models.IntegerField(
                blank=True,
                help_text="Број дана у односу на Васкрс",
                null=True,
                verbose_name="помак у данима",
            ),
        ),
        migrations.AddField(
            model_name="slava",
            name="offset_nedelje",
            field=models.IntegerField(
                blank=True,
                help_text="Број недеља у односу на Васкрс",
                null=True,
                verbose_name="помак у недељама",
            ),
        ),
        migrations.AddField(
            model_name="slava",
            name="pokretni",
            field=models.BooleanField(
                default=False,
                help_text="Празник који се рачуна у односу на Васкрс",
                verbose_name="покретни празник",
            ),
        ),
        migrations.AddField(
            model_name="slava",
            name="post",
            field=models.BooleanField(default=False, verbose_name="пост"),
        ),
        migrations.AddField(
            model_name="slava",
            name="post_do",
            field=models.IntegerField(
                blank=True,
                help_text="Крај поста у данима од Васкрса",
                null=True,
                verbose_name="крај поста (дани)",
            ),
        ),
        migrations.AddField(
            model_name="slava",
            name="post_od",
            field=models.IntegerField(
                blank=True,
                help_text="Почетак поста у данима од Васкрса",
                null=True,
                verbose_name="почетак поста (дани)",
            ),
        ),
    ]
