# Generated by Django 6.0.1 on 2026-05-17 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0005_move_slava_to_kalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsvestenik',
            name='adresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registar.adresa', verbose_name='адреса'),
        ),
        migrations.AddField(
            model_name='svestenik',
            name='adresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registar.adresa', verbose_name='адреса'),
        ),
    ]
