# Generated by Django 6.0.1 on 2026-06-14 09:51

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0006_historicalsvestenik_user_svestenik_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAdresa",
            fields=[
                (
                    "uid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "ulica",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="улица"
                    ),
                ),
                (
                    "broj",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="број"
                    ),
                ),
                (
                    "sprat",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="спрат"
                    ),
                ),
                (
                    "broj_stana",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="број стана"
                    ),
                ),
                (
                    "mesto",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="место",
                    ),
                ),
                (
                    "postkod",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="поштански број",
                    ),
                ),
                (
                    "primedba",
                    models.TextField(blank=True, default="", verbose_name="примедба"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "svestenik",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Свештеник задужен за ову улицу (за васкршњу водицу).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.svestenik",
                        verbose_name="свештеник (улица)",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Адреса",
                "verbose_name_plural": "historical Адресе",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUkucanin",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "ime_ukucana",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uloga",
                    models.CharField(
                        choices=[
                            ("домаћин", "Домаћин"),
                            ("супружник", "Супружник/ка"),
                            ("дете", "Дете"),
                            ("рођак", "Рођак/сродник"),
                            ("остало", "Остало"),
                        ],
                        default="остало",
                        max_length=30,
                    ),
                ),
                (
                    "preminuo",
                    models.BooleanField(default=False, verbose_name="преминуо"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "domacinstvo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.domacinstvo",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "osoba",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="registar.osoba",
                        verbose_name="особа",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Укућанин",
                "verbose_name_plural": "historical Укућани",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
