# Generated by Django 6.0.1 on 2026-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0006_historicalsvestenik_adresa_svestenik_adresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalosoba",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="имејл"
            ),
        ),
        migrations.AddField(
            model_name="osoba",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="имејл"
            ),
        ),
    ]
