# Generated by Django 6.0.1 on 2026-06-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0007_historicaladresa_historicalukucanin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsvestenik",
            name="ime",
            field=models.CharField(max_length=100, verbose_name="име"),
        ),
        migrations.AlterField(
            model_name="historicalsvestenik",
            name="mesto_rodjenja",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="место рођења"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsvestenik",
            name="prezime",
            field=models.CharField(max_length=100, verbose_name="презиме"),
        ),
        migrations.AlterField(
            model_name="svestenik",
            name="ime",
            field=models.CharField(max_length=100, verbose_name="име"),
        ),
        migrations.AlterField(
            model_name="svestenik",
            name="mesto_rodjenja",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="место рођења"
            ),
        ),
        migrations.AlterField(
            model_name="svestenik",
            name="prezime",
            field=models.CharField(max_length=100, verbose_name="презиме"),
        ),
        migrations.AlterField(
            model_name="zanimanje",
            name="sifra",
            field=models.CharField(max_length=50, verbose_name="шифра"),
        ),
        migrations.AlterField(
            model_name="zanimanje",
            name="zenski_naziv",
            field=models.CharField(
                max_length=255, null=True, verbose_name="женски назив"
            ),
        ),
    ]
