# Generated by Django 6.0.1 on 2026-05-20 11:21

import registar.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0007_historicalosoba_email_osoba_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domacinstvo",
            name="tel_fiksni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="фиксни телефон",
            ),
        ),
        migrations.AlterField(
            model_name="domacinstvo",
            name="tel_mobilni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="мобилни телефон",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldomacinstvo",
            name="tel_fiksni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="фиксни телефон",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldomacinstvo",
            name="tel_mobilni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="мобилни телефон",
            ),
        ),
        migrations.AlterField(
            model_name="historicalosoba",
            name="tel_fiksni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="фиксни телефон",
            ),
        ),
        migrations.AlterField(
            model_name="historicalosoba",
            name="tel_mobilni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="мобилни телефон",
            ),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="tel_fiksni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="фиксни телефон",
            ),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="tel_mobilni",
            field=registar.fields.TenantPhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="мобилни телефон",
            ),
        ),
    ]
