# Generated by Django 6.0.1 on 2026-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0008_alter_domacinstvo_tel_fiksni_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domacinstvo",
            options={
                "ordering": [
                    "adresa__ulica",
                    "adresa__broj",
                    "domacin__prezime",
                    "domacin__ime",
                ],
                "verbose_name": "Домаћинство",
                "verbose_name_plural": "Домаћинства",
            },
        ),
        migrations.AlterModelOptions(
            name="krstenje",
            options={
                "managed": True,
                "ordering": ["-datum"],
                "verbose_name": "Крштење",
                "verbose_name_plural": "Крштења",
            },
        ),
        migrations.AlterModelOptions(
            name="vencanje",
            options={
                "managed": True,
                "ordering": ["-datum"],
                "verbose_name": "Венчање",
                "verbose_name_plural": "Венчања",
            },
        ),
        migrations.AlterField(
            model_name="historicalosoba",
            name="pol",
            field=models.CharField(
                blank=True,
                choices=[("М", "мушки"), ("Ж", "женски")],
                db_index=True,
                max_length=1,
                null=True,
                verbose_name="пол",
            ),
        ),
        migrations.AlterField(
            model_name="osoba",
            name="pol",
            field=models.CharField(
                blank=True,
                choices=[("М", "мушки"), ("Ж", "женски")],
                db_index=True,
                max_length=1,
                null=True,
                verbose_name="пол",
            ),
        ),
        migrations.AddIndex(
            model_name="adresa",
            index=models.Index(fields=["ulica", "broj"], name="adresa_ulica_broj_idx"),
        ),
    ]
