# Generated by Django 6.0.1 on 2026-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registar", "0008_alter_domacinstvo_tel_fiksni_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsvestenik",
            name="zvanje",
            field=models.CharField(
                choices=[
                    ("патријарх српски", "патријарх српски"),
                    ("јереј", "јереј"),
                    ("протојереј", "протојереј"),
                    ("протојереј-ставрофор", "протојереј-ставрофор"),
                    ("протонамесник", "протонамесник"),
                    ("администратор", "администратор"),
                    ("митрополит", "митрополит"),
                ],
                max_length=30,
                verbose_name="звање",
            ),
        ),
        migrations.AlterField(
            model_name="svestenik",
            name="zvanje",
            field=models.CharField(
                choices=[
                    ("патријарх српски", "патријарх српски"),
                    ("јереј", "јереј"),
                    ("протојереј", "протојереј"),
                    ("протојереј-ставрофор", "протојереј-ставрофор"),
                    ("протонамесник", "протонамесник"),
                    ("администратор", "администратор"),
                    ("митрополит", "митрополит"),
                ],
                max_length=30,
                verbose_name="звање",
            ),
        ),
    ]
