# Generated by Django 6.0.1 on 2026-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0010_alter_historicalsvestenik_zvanje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresa',
            name='broj',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='број'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='dete_blizanac',
            field=models.BooleanField(default=False, verbose_name='дете близанац'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='dete_sa_telesnom_manom',
            field=models.BooleanField(default=False, verbose_name='дете са телесном маном'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='dete_vanbracno',
            field=models.BooleanField(default=False, verbose_name='ванбрачно дете'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='dete_blizanac',
            field=models.BooleanField(default=False, verbose_name='дете близанац'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='dete_sa_telesnom_manom',
            field=models.BooleanField(default=False, verbose_name='дете са телесном маном'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='dete_vanbracno',
            field=models.BooleanField(default=False, verbose_name='ванбрачно дете'),
        ),
    ]
