# Generated by Django 6.0.1 on 2026-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0012_rename_krstenje_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='blizanac',
            field=models.BooleanField(default=False, verbose_name='близанац'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='ime_blizanca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='име близанца'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='po_redu',
            field=models.CharField(blank=True, null=True, verbose_name='по реду мајци'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='telesna_mana',
            field=models.BooleanField(default=False, verbose_name='телесна мана'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='vanbracno',
            field=models.BooleanField(default=False, verbose_name='ванбрачно'),
        ),
        migrations.AlterField(
            model_name='historicalkrstenje',
            name='zivorodjeno',
            field=models.BooleanField(default=True, verbose_name='живорођено'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='blizanac',
            field=models.BooleanField(default=False, verbose_name='близанац'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='ime_blizanca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='име близанца'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='po_redu',
            field=models.CharField(blank=True, null=True, verbose_name='по реду мајци'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='telesna_mana',
            field=models.BooleanField(default=False, verbose_name='телесна мана'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='vanbracno',
            field=models.BooleanField(default=False, verbose_name='ванбрачно'),
        ),
        migrations.AlterField(
            model_name='krstenje',
            name='zivorodjeno',
            field=models.BooleanField(default=True, verbose_name='живорођено'),
        ),
    ]
