# Generated by Django 6.0.1 on 2026-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registar', '0013_alter_historicalkrstenje_blizanac_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svestenik',
            options={'managed': True, 'ordering': ['prezime', 'ime'], 'verbose_name': 'Свештеник', 'verbose_name_plural': 'Свештеници'},
        ),
        migrations.AlterField(
            model_name='adresa',
            name='mesto',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='место'),
        ),
        migrations.AddIndex(
            model_name='krstenje',
            index=models.Index(fields=['godina_registracije', 'knjiga', 'strana', 'broj'], name='krstenje_protocol_idx'),
        ),
        migrations.AddIndex(
            model_name='osoba',
            index=models.Index(fields=['created'], name='osoba_created_idx'),
        ),
        migrations.AddIndex(
            model_name='svestenik',
            index=models.Index(fields=['created'], name='svestenik_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vencanje',
            index=models.Index(fields=['godina_registracije', 'knjiga', 'strana', 'broj'], name='vencanje_protocol_idx'),
        ),
    ]
