# Generated by Django 6.0.1 on 2026-06-14 13:39

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


def create_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    UserMembership = apps.get_model("tenants", "UserMembership")
    User = apps.get_model(
        settings.AUTH_USER_MODEL.split(".")[0],
        settings.AUTH_USER_MODEL.split(".")[1],
    )
    tenant, _ = Tenant.objects.get_or_create(
        schema_name="crkva_sv_petke_cukarica",
        defaults={
            "naziv": "Парохија Чукарица",
            "parohija_naziv": "Парохија Чукарица",
            "is_active": True,
            "is_default": True,
        },
    )
    if not tenant.is_default:
        Tenant.objects.exclude(pk=tenant.pk).update(is_default=False)
        tenant.is_default = True
        tenant.save()
    schema_editor.execute("CREATE SCHEMA IF NOT EXISTS crkva_sv_petke_cukarica")
    for user in User.objects.filter(is_active=True, is_staff=True):
        UserMembership.objects.get_or_create(
            user=user,
            tenant=tenant,
            defaults={"role": "admin", "is_default": True},
        )


def remove_default_tenant(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.filter(schema_name="crkva_sv_petke_cukarica").delete()
    schema_editor.execute("DROP SCHEMA IF EXISTS crkva_sv_petke_cukarica CASCADE")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        help_text="Кориснички видљив назив (нпр. „Парохија Чукарица“).",
                        max_length=200,
                        verbose_name="назив парохије",
                    ),
                ),
                (
                    "parohija_naziv",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Име парохије за приказ. У свакој парохијској шеми постоји сопствена Parohija инстанца; ово је само display label.",
                        max_length=200,
                        verbose_name="парохија (име)",
                    ),
                ),
                (
                    "mesto",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Место парохије како се штампа у заглављу сертификата, у локативу иза „у“ (нпр. „Београду“, „Чукарици“, „Амстердаму“).",
                        max_length=200,
                        verbose_name="место (за штампу)",
                    ),
                ),
                (
                    "default_phone_region",
                    models.CharField(
                        default="RS",
                        help_text="ISO 3166-1 alpha-2 (нпр. RS, NL, DE, AT, CH). Када корисник укуца локални број без +префикса, систем користи овај код за тумачење.",
                        max_length=2,
                        verbose_name="подразумевана земља за телефон",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активан"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Парохија коју виде корисници без експлицитно додељене парохије.",
                        verbose_name="подразумевани",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Парохија",
                "verbose_name_plural": "Парохије",
                "db_table": "tenants_tenant",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="tenants_tenant_only_one_default",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домен",
                "verbose_name_plural": "Домени",
                "db_table": "tenants_domain",
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("kancelarija", "Канцеларија"),
                            ("svestenstvo", "Свештенство"),
                            ("pregled", "Преглед"),
                        ],
                        default="pregled",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Парохија у коју корисник аутоматски улази после пријаве.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Деактивирано чланство закључава корисника из ове парохије, али не утиче на глобални налог нити на приступ другим парохијама.",
                        verbose_name="активно чланство",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Чланство корисника",
                "verbose_name_plural": "Чланства корисника",
                "db_table": "tenants_user_membership",
                "unique_together": {("user", "tenant")},
            },
        ),
        migrations.RunPython(create_default_tenant, remove_default_tenant),
    ]
