# Generated by Django 6.0.1 on 2026-05-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registar", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        help_text="Кориснички видљив назив (нпр. „Парохија Чукарица“).",
                        max_length=200,
                        verbose_name="назив тенанта",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        help_text="Postgres schema име за изолацију података. Реално користи се од Фазе 2.",
                        max_length=63,
                        unique=True,
                        verbose_name="schema name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активан"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Тенант који видe корисници без експлицитно додељене парохије.",
                        verbose_name="подразумевани",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parohija",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant",
                        to="registar.parohija",
                        verbose_name="парохија",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тенант",
                "verbose_name_plural": "Тенанти",
                "db_table": "tenants_tenant",
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор парохије"),
                            ("member", "Члан парохије"),
                            ("viewer", "Преглед без измена"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Тенант у који корисник аутоматски улази после пријаве.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Чланство корисника",
                "verbose_name_plural": "Чланства корисника",
                "db_table": "tenants_user_membership",
            },
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="tenants_tenant_only_one_default",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermembership",
            unique_together={("user", "tenant")},
        ),
    ]
