# Generated by Django 6.0.1 on 2026-05-16 16:05

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "naziv",
                    models.CharField(
                        help_text="Кориснички видљив назив (нпр. „Парохија Чукарица“).",
                        max_length=200,
                        verbose_name="назив тенанта",
                    ),
                ),
                (
                    "parohija_naziv",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Име парохије за приказ. У сваком тенантовом шеми постоји сопствена Parohija инстанца; ово је само display label.",
                        max_length=200,
                        verbose_name="парохија (име)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активан"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Тенант који видe корисници без експлицитно додељене парохије.",
                        verbose_name="подразумевани",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Тенант",
                "verbose_name_plural": "Тенанти",
                "db_table": "tenants_tenant",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="tenants_tenant_only_one_default",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домен",
                "verbose_name_plural": "Домени",
                "db_table": "tenants_domain",
            },
        ),
        migrations.CreateModel(
            name="UserMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор парохије"),
                            ("member", "Члан парохије"),
                            ("viewer", "Преглед без измена"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Тенант у који корисник аутоматски улази после пријаве.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Чланство корисника",
                "verbose_name_plural": "Чланства корисника",
                "db_table": "tenants_user_membership",
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
