# Generated by Django 6.0.1 on 2026-06-27 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="parohija_naziv",
        ),
    ]
