# Generated by Django 6.0.1 on 2026-05-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_remap_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={"verbose_name": "Парохија", "verbose_name_plural": "Парохије"},
        ),
        migrations.AlterField(
            model_name="tenant",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Парохија коју виде корисници без експлицитно додељене парохије.",
                verbose_name="подразумевани",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="naziv",
            field=models.CharField(
                help_text="Кориснички видљив назив (нпр. „Парохија Чукарица“).",
                max_length=200,
                verbose_name="назив парохије",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="parohija_naziv",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Име парохије за приказ. У свакој парохијској шеми постоји сопствена Parohija инстанца; ово је само display label.",
                max_length=200,
                verbose_name="парохија (име)",
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Парохија у коју корисник аутоматски улази после пријаве.",
            ),
        ),
    ]
