# Generated by Django 6.0.1 on 2026-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_alter_tenant_options_alter_tenant_is_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="default_phone_region",
            field=models.CharField(
                default="RS",
                help_text="ISO 3166-1 alpha-2 (нпр. RS, NL, DE, AT, CH). Када корисник укуца локални број без +префикса, систем користи овај код за тумачење.",
                max_length=2,
                verbose_name="подразумевана земља за телефон",
            ),
        ),
    ]
