name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-junit
        pip install django==4.1.2 \
                    django-environ==0.9.0 \
                    django-import-export==3.0.1 \
                    django-restframework==0.0.1 \
                    djangorestframework==3.14.0 \
                    psycopg2-binary==2.9.5 \
                    python-dateutil==2.8.2
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
